image: "rust:latest"

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

cache:
  paths:
  - cargo/
  - target/

stages:
  - check
  - deploy

before_script:
  - export CARGO_HOME="$CI_PROJECT_DIR/cargo"
  - rustup --version
  - rustc --version
  - cargo --version
  - cargo install cargo-make



check:
  stage: check
  script:
  - cargo install cargo-make
  - cargo make check

fmt:
  stage: check
  script:
  - cargo make fmt

clippy:
  stage: check
  script:
  - cargo make clippy

pages:
  stage: deploy
  script:
  - cargo make deploy public
  artifacts:
    paths:
    - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
