image: "rust:latest"

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

cache:
  paths:
  - cargo/
  - target/

stages:
  - check
  - deploy

before_script:
  - export CARGO_HOME="$CI_PROJECT_DIR/cargo"
  - rustup --version
  - rustc --version
  - cargo --version



check:
  stage: check
  script:
  - cargo install cargo-make
  - cargo make check

fmt:
  stage: check
  script:
  - rustup component add rustfmt
  - cargo fmt --all -- --check

clippy:
  stage: check
  script:
  - rustup component add clippy
  - cargo clippy -- -D warnings

pages:
  stage: deploy
  script:
  - cargo install cargo-make
  - cargo make build_release
  - mkdir public/
  - cp -r index.html static/ public/
  - mv pkg/ public/
  artifacts:
    paths:
    - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
