image: "rust:latest"

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

cache:
  paths:
  - cargo/
  - target/
  - rustup/

before_script:
  - rustup --version
  - rustc --version
  - cargo --version
  - cargo install cargo-make

pages:
  stage: deploy
  script:
  - cargo make build_release
  - mkdir public/
  - cp -r index.html static/ public/
  - mv pkg/ public/
  artifacts:
    paths:
    - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

test:
  stage: test
  script:
  - cargo make check
