title: Damian Szewczyk
email: damian.szewczyk111@gmail.com
description: >-
  Personal blog for sharing thoughts about different practices and patters 
  used to create clean and efficient software

domain: damszew.github.io
url: "https://damszew.github.io"
github_username: damszew
linkedin_username: szewczyk-damian
twitter_username: damszew

theme: jekyll-theme-yat
# Theme specific settings
defaults:
  home:
    heading: damszew.github.io
    subheading: A personal blog

plugins:
  - jekyll-feed
