title: Damian Szewczyk
email: damian.szewczyk111@gmail.com
description: >-
  Personal blog for sharing thoughts about different practices and patters 
  used to create clean and efficient software

domain: damszew.github.io
url: "https://damszew.github.io"
github_username: damszew
linkedin_username: szewczyk-damian
twitter_username: damszew

theme: jekyll-theme-yat
# Theme specific settings
banner:
  image: "assets/images/leaves.jpg"
  background: "#000000"
  opacity: 0.7

translate_langs: []
night_mode: "manual"
brand_color: "#588E5D"
code_badge:
  enabled: "true"
  color: "#fff"
  background_color: "#588E5D"
  text_transform: "lowercase"  # ("uppercase", "lowercase", "capitalize")

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/leaves.jpg
      alt: Photo of dark green leaves

plugins:
  - jekyll-feed
