title: TDD Skills
email: damian.szewczyk111@gmail.com
description: >-
  Blog about exploring how TDD (and related methodologies like BDD, ATDD
  or even Continuos Delivery) allow us devs to write better quality software, faster.

domain: damszew.github.io
url: "https://damszew.github.io"
baseurl: "/tdd-skills"
github_username: damszew
linkedin_username: szewczyk-damian
twitter_username: damszew

theme: jekyll-theme-yat

plugins:
  - jekyll-feed
