[package]
name = "appname"
version = "0.1.0"
authors = ["Damian Szewczyk <damian.szewczyk111@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]


[dependencies]
seed = "0.6.0"
wasm-bindgen = "0.2.50"

[profile.release]  # Attempts to minimize file size
lto = true
opt-level = 'z'
